### ISSUE TITLE
Need a Data Base!

### ISSUE THREAD

**Issue by yizongk** [opensource-ny/OpenSource-NY#30]
We need a data base, let's try PostgresQL

**Comment by Chocolate-Spaghet** [comment]
How's MongoDB?

**Comment by yizongk** [comment]
MongoDB isn't relational, and PostgresQL is. 

I think we would be better off if we could write statement like select all from user blah blah blah than grabbing a JSON stored in MongoDB and then parsing it, which could take time. 

But then again, Javascript has nice API to play with JSON. What you think about it?

**Comment by Chocolate-Spaghet** [comment]
I'm good with either or. PostgresQL is good if we know what we are going to be storing exactly (you can store JSON in PSQL), but MongoDB has the advantage of storing pretty much anything. I think Mongo will be better since we may want to expand the things we store down the road. Mongo also has a very good query system, and can be somewhat used as a relational database. In general, I think Mongo will be better for this project.

**Comment by yizongk** [comment]
Ok! I have no problem with your reasoning. We will go with MongoDB!

**Comment by Fioringo** [comment]
This issue is resolved as the project is using MongoDB now. Thank you for the discussion! 🎉
