### ISSUE TITLE
Repo input field takes in a string with spaces in front or in the back will not work

### ISSUE THREAD

**Issue by yizongk** [opensource-ny/OpenSource-NY#67]
Entering 'opensource-ny/OpenSource-NY' will fetch PR data.

but entering '  opensource-ny/OpenSource-NY' or 'opensource-ny/OpenSource-NY    ' will not work

should have some way to parse those spaces out

**Comment by yizongk** [comment]
Commit 4eb1644ac28280face0191ad26721b967d996034  sort of fixes it. 

Removes not only leading/trailing white spaces, but also white spaces in-between!

So a string such as " ope nsource-ny/OpenSo urce-NY " will be parsed as "opensource-ny.OpenSource-NY"

Will need to fix this.

**Comment by Chocolate-Spaghet** [comment]
Why do the white spaces in between matter?

**Comment by yizongk** [comment]
Well, because "open   source-ny/OpenSource-NY" is not syntactically considered a valid repo name. But it's up to you guys, this bug just irritates me. I will fix it unless you guys object to it being a bug

**Comment by Chocolate-Spaghet** [comment]
I think it's a feature, since it doesn't allow for spaces in between. Sometimes you may type a space where you didn't mean to, and this way there is no frustration about missing that. I think [4eb1644](https://github.com/opensource-ny/OpenSource-NY/commit/4eb1644ac28280face0191ad26721b967d996034) fixes it in a good way.

**Comment by yizongk** [comment]
alright! Commit 4eb1644ac28280face0191ad26721b967d996034 Fixes this, let's close it. :)
